<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>c2ad19e3-40b5-406c-ae2e-216fa1b3e068</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="appsettings.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Controllers\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\RepositoryPatternWithUOW.Core\RepositoryPatternWithUOW.Core.csproj" />
	  <ProjectReference Include="..\RepositoryPatternWithUOW.Ef\RepositoryPatternWithUOW.Ef.csproj" />
	</ItemGroup>

</Project>
